/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SketchesRouteImport } from './routes/sketches'
import { Route as SketchbookRouteImport } from './routes/sketchbook'
import { Route as FanWallRouteImport } from './routes/fan-wall'
import { Route as CommissionRouteImport } from './routes/commission'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SketchesRoute = SketchesRouteImport.update({
  id: '/sketches',
  path: '/sketches',
  getParentRoute: () => rootRouteImport,
} as any)
const SketchbookRoute = SketchbookRouteImport.update({
  id: '/sketchbook',
  path: '/sketchbook',
  getParentRoute: () => rootRouteImport,
} as any)
const FanWallRoute = FanWallRouteImport.update({
  id: '/fan-wall',
  path: '/fan-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionRoute = CommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/colors': typeof ColorsRoute
  '/commission': typeof CommissionRoute
  '/fan-wall': typeof FanWallRoute
  '/sketchbook': typeof SketchbookRoute
  '/sketches': typeof SketchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/colors': typeof ColorsRoute
  '/commission': typeof CommissionRoute
  '/fan-wall': typeof FanWallRoute
  '/sketchbook': typeof SketchbookRoute
  '/sketches': typeof SketchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/colors': typeof ColorsRoute
  '/commission': typeof CommissionRoute
  '/fan-wall': typeof FanWallRoute
  '/sketchbook': typeof SketchbookRoute
  '/sketches': typeof SketchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/colors' | '/commission' | '/fan-wall' | '/sketchbook' | '/sketches'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/colors' | '/commission' | '/fan-wall' | '/sketchbook' | '/sketches'
  id: '__root__' | '/' | '/about' | '/colors' | '/commission' | '/fan-wall' | '/sketchbook' | '/sketches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ColorsRoute: typeof ColorsRoute
  CommissionRoute: typeof CommissionRoute
  FanWallRoute: typeof FanWallRoute
  SketchbookRoute: typeof SketchbookRoute
  SketchesRoute: typeof SketchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sketches': {
      id: '/sketches'
      path: '/sketches'
      fullPath: '/sketches'
      preLoaderRoute: typeof SketchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sketchbook': {
      id: '/sketchbook'
      path: '/sketchbook'
      fullPath: '/sketchbook'
      preLoaderRoute: typeof SketchbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan-wall': {
      id: '/fan-wall'
      path: '/fan-wall'
      fullPath: '/fan-wall'
      preLoaderRoute: typeof FanWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission': {
      id: '/commission'
      path: '/commission'
      fullPath: '/commission'
      preLoaderRoute: typeof CommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ColorsRoute: ColorsRoute,
  CommissionRoute: CommissionRoute,
  FanWallRoute: FanWallRoute,
  SketchbookRoute: SketchbookRoute,
  SketchesRoute: SketchesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
